<?php
$channels = array(
  array('Station' => 'bbc','Channel' => 'top news','Category' => 'top news','Url' => 'http://feeds.bbci.co.uk/news/rss.xml'),
  array('Station' => 'bbc','Channel' => 'world','Category' => 'world','Url' => 'http://feeds.bbci.co.uk/news/world/rss.xml'),
  array('Station' => 'bbc','Channel' => 'uk','Category' => 'uk','Url' => 'http://feeds.bbci.co.uk/news/uk/rss.xml'),
  array('Station' => 'bbc','Channel' => 'middle east','Category' => 'middle east','Url' => 'http://feeds.bbci.co.uk/news/world/middle_east/rss.xml'),
  array('Station' => 'bbc','Channel' => 'africa','Category' => 'africa','Url' => 'http://feeds.bbci.co.uk/news/world/africa/rss.xml'),
  array('Station' => 'bbc','Channel' => 'asia','Category' => 'asia','Url' => 'http://feeds.bbci.co.uk/news/world/asia/rss.xml'),
  array('Station' => 'bbc','Channel' => 'us & canada','Category' => 'americas','Url' => 'http://feeds.bbci.co.uk/news/world/us_and_canada/rss.xml'),
  array('Station' => 'bbc','Channel' => 'business','Category' => 'business','Url' => 'http://feeds.bbci.co.uk/news/business/rss.xml'),
  array('Station' => 'bbc','Channel' => 'health','Category' => 'health','Url' => 'http://feeds.bbci.co.uk/news/health/rss.xml'),
  array('Station' => 'bbc','Channel' => 'environment','Category' => 'environment','Url' => 'http://feeds.bbci.co.uk/news/science_and_environment/rss.xml'),
  array('Station' => 'bbc','Channel' => 'technology','Category' => 'technology','Url' => 'http://feeds.bbci.co.uk/news/technology/rss.xml'),

  

  array('Station' => 'cnn','Channel' => 'top news','Category' => 'top news','Url' => 'http://rss.cnn.com/rss/edition.rss'),
  array('Station' => 'cnn','Channel' => 'world','Category' => 'world','Url' => 'http://rss.cnn.com/rss/edition_world.rss'),
  array('Station' => 'cnn','Channel' => 'africa','Category' => 'africa','Url' => 'http://rss.cnn.com/rss/edition_africa.rss'),
  array('Station' => 'cnn','Channel' => 'us','Category' => 'us','Url' => 'http://rss.cnn.com/rss/edition_us.rss'),
  array('Station' => 'cnn','Channel' => 'asia','Category' => 'asia','Url' => 'http://rss.cnn.com/rss/edition_asia.rss'),
  array('Station' => 'cnn','Channel' => 'europe','Category' => 'europe','Url' => 'http://rss.cnn.com/rss/edition_europe.rss'),
  array('Station' => 'cnn','Channel' => 'middle east','Category' => 'middle east','Url' => 'http://rss.cnn.com/rss/edition_meast.rss'),
  array('Station' => 'cnn','Channel' => 'business','Category' => 'business','Url' => 'http://rss.cnn.com/rss/edition_business.rss'),
  array('Station' => 'cnn','Channel' => 'technology','Category' => 'technology','Url' => 'http://rss.cnn.com/rss/edition_technology.rss'),
  array('Station' => 'cnn','Channel' => 'space','Category' => 'space','Url' => 'http://rss.cnn.com/rss/edition_space.rss'),

  array('Station' => 'press tv','Channel' => 'top news','Category' => 'top news','Url' => 'http://edition.presstv.ir/rss'),
  array('Station' => 'press tv','Channel' => 'middle east','Category' => 'middle east','Url' => 'http://edition.presstv.ir/rss/?section=3510202'),
  array('Station' => 'press tv','Channel' => 'americas','Category' => 'americas','Url' => 'http://edition.presstv.ir/rss/?section=3510203'),
  array('Station' => 'press tv','Channel' => 'uk','Category' => 'uk','Url' => 'http://edition.presstv.ir/rss/?section=3510218'),
  array('Station' => 'press tv','Channel' => 'asia','Category' => 'asia','Url' => 'http://edition.presstv.ir/rss/?section=3510204'),
  array('Station' => 'press tv','Channel' => 'africa','Category' => 'africa','Url' => 'http://edition.presstv.ir/rss/?section=3510204'),
  array('Station' => 'press tv','Channel' => 'technology','Category' => 'technology','Url' => 'http://edition.presstv.ir/rss/?section=3510208'),
  array('Station' => 'press tv','Channel' => 'health','Category' => 'health','Url' => 'http://edition.presstv.ir/rss/?section=3510210'),
  array('Station' => 'press tv','Channel' => 'business','Category' => 'business','Url' => 'http://edition.presstv.ir/rss/?section=3510213'),

  array('Station' => 'nasa','Channel' => 'breaking news','Category' => 'top news','Url' => 'http://www.nasa.gov/rss/dyn/breaking_news.rss'),
  array('Station' => 'nasa','Channel' => 'education','Category' => 'space','Url' => 'http://www.nasa.gov/rss/dyn/educationnews.rss'),

  
  array('Station' => 'sky','Channel' => 'top news','Category' => 'top news','Url' => 'http://news.sky.com/feeds/rss/home.xml'),
  array('Station' => 'sky','Channel' => 'uk','Category' => 'uk','Url' => 'http://news.sky.com/feeds/rss/uk.xml'),
  array('Station' => 'sky','Channel' => 'world','Category' => 'world','Url' => 'http://news.sky.com/feeds/rss/world.xml'),
  array('Station' => 'sky','Channel' => 'us','Category' => 'us','Url' => 'http://news.sky.com/feeds/rss/us.xml'),
  array('Station' => 'sky','Channel' => 'business','Category' => 'business','Url' => 'http://news.sky.com/feeds/rss/business.xml'),
  array('Station' => 'sky','Channel' => 'technology','Category' => 'technology','Url' => 'http://news.sky.com/feeds/rss/technology.xml'),



  array('Station' => 'reuters','Channel' => 'top news','Category' => 'top news','Url' => 'http://feeds.reuters.com/reuters/topNews'),
  array('Station' => 'reuters','Channel' => 'business','Category' => 'business','Url' => 'http://feeds.reuters.com/reuters/businessNews'),
  array('Station' => 'reuters','Channel' => 'global markets','Category' => 'markets','Url' => 'http://feeds.reuters.com/reuters/globalmarketsNews'),
  array('Station' => 'reuters','Channel' => 'environment','Category' => 'environment','Url' => 'http://feeds.reuters.com/reuters/environment'),
  array('Station' => 'reuters','Channel' => 'health','Category' => 'health','Url' => 'http://feeds.reuters.com/reuters/healthNews'),
  array('Station' => 'reuters','Channel' => 'money','Category' => 'money','Url' => 'http://feeds.reuters.com/news/wealth'),
  array('Station' => 'reuters','Channel' => 'science','Category' => 'science','Url' => 'http://feeds.reuters.com/reuters/scienceNews'),
  array('Station' => 'reuters','Channel' => 'technology','Category' => 'technology','Url' => 'http://feeds.reuters.com/reuters/technologyNews'),

  array('Station' => 'reuters','Channel' => 'us','Category' => 'us','Url' => 'http://feeds.reuters.com/Reuters/domesticNews'),
  array('Station' => 'reuters','Channel' => 'world','Category' => 'world','Url' => 'http://feeds.reuters.com/Reuters/worldNews'),


  array('Station' => 'rt news','Channel' => 'daily','Category' => 'top news','Url' => 'http://rt.com/rss/'),
  array('Station' => 'rt news','Channel' => 'us','Category' => 'us','Url' => 'http://rt.com/rss/usa/'),
  array('Station' => 'rt news','Channel' => 'business','Category' => 'business','Url' => 'http://rt.com/rss/business/'),


  array('Station' => 'new york times','Channel' => 'science','Category' => 'science','Url' => 'http://rss.nytimes.com/services/xml/rss/nyt/Science.xml'),
  array('Station' => 'new york times','Channel' => 'health','Category' => 'health','Url' => 'http://www.nytimes.com/services/xml/rss/nyt/health.xml'),
  array('Station' => 'new york times','Channel' => 'space','Category' => 'space','Url' => 'http://rss.nytimes.com/services/xml/rss/nyt/Space.xml'),
  array('Station' => 'new york times','Channel' => 'technology','Category' => 'technology','Url' => 'http://www.nytimes.com/services/xml/rss/nyt/Technology.xml'),
  array('Station' => 'new york times','Channel' => 'world','Category' => 'world','Url' => 'http://www.nytimes.com/services/xml/rss/nyt/International.xml'),
  array('Station' => 'new york times','Channel' => 'africa','Category' => 'africa','Url' => 'http://www.nytimes.com/services/xml/rss/nyt/Africa.xml'),
  array('Station' => 'new york times','Channel' => 'usa','Category' => 'americas','Url' => 'http://www.nytimes.com/services/xml/rss/nyt/Americas.xml'),
  array('Station' => 'new york times','Channel' => 'aisa','Category' => 'asia','Url' => 'http://www.nytimes.com/services/xml/rss/nyt/AsiaPacific.xml'),
  array('Station' => 'new york times','Channel' => 'europe','Category' => 'europe','Url' => 'http://www.nytimes.com/services/xml/rss/nyt/Europe.xml'),

  array('Station' => 'new york times','Channel' => 'middle east','Category' => 'middle east','Url' => 'http://www.nytimes.com/services/xml/rss/nyt/MiddleEast.xml'),
  array('Station' => 'new york times','Channel' => 'business','Category' => 'business','Url' => 'http://rss.nytimes.com/services/xml/rss/nyt/InternationalBusiness.xml'),
  array('Station' => 'washington post','Channel' => 'africa','Category' => 'africa','Url' => 'http://www.washingtonpost.com/wp-dyn/rss/world/africa/index.xml'),
  array('Station' => 'washington post','Channel' => 'health','Category' => 'health','Url' => 'http://www.washingtonpost.com/wp-dyn/rss/health/index.xml'),
  array('Station' => 'washington post','Channel' => 'science','Category' => 'science','Url' => 'http://www.washingtonpost.com/wp-dyn/rss/nation/science/index.xml'),
  array('Station' => 'washington post','Channel' => 'technology','Category' => 'technology','Url' => 'http://www.washingtonpost.com/wp-dyn/rss/technology/index.xml'),
  array('Station' => 'washington post','Channel' => 'business','Category' => 'business','Url' => 'http://www.washingtonpost.com/wp-dyn/rss/business/index.xml'),
  array('Station' => 'washington post','Channel' => 'world','Category' => 'world','Url' => 'http://www.washingtonpost.com/wp-dyn/rss/world/index.xml'),
  array('Station' => 'washington post','Channel' => 'north america','Category' => 'americas','Url' => 'http://www.washingtonpost.com/wp-dyn/rss/world/northamerica/index.xml'),
  array('Station' => 'washington post','Channel' => 'south america','Category' => 'americas','Url' => 'http://www.washingtonpost.com/wp-dyn/rss/world/southamerica/index.xml'),
  array('Station' => 'washington post','Channel' => 'central america','Category' => 'americas','Url' => 'http://www.washingtonpost.com/wp-dyn/rss/world/centralamerica/index.xml'),
  array('Station' => 'washington post','Channel' => 'aisa','Category' => 'asia','Url' => 'http://www.washingtonpost.com/wp-dyn/rss/world/asia/index.xml'),
  array('Station' => 'washington post','Channel' => 'europe','Category' => 'europe','Url' => 'http://www.washingtonpost.com/wp-dyn/rss/world/europe/index.xml'),
  array('Station' => 'washington post','Channel' => 'middle east','Category' => 'middle east','Url' => 'http://www.washingtonpost.com/wp-dyn/rss/world/mideast/index.xml'),


  array('Station' => 'aljazeera','Channel' => 'home','Category' => 'world','Url' => 'http://www.aljazeera.com/services/rss/?postingid=2007731105943979989'),

  array('Station' => 'daily mail','Channel' => 'home','Category' => 'europe','Url' => 'http://www.dailymail.co.uk/home/index.rss'),
  array('Station' => 'daily mail','Channel' => 'health','Category' => 'health','Url' => 'http://www.dailymail.co.uk/health/index.rss'),
  array('Station' => 'daily mail','Channel' => 'science','Category' => 'science','Url' => 'http://www.dailymail.co.uk/sciencetech/index.rss'),
  array('Station' => 'daily mail','Channel' => 'headlines','Category' => 'top news','Url' => 'http://www.dailymail.co.uk/news/headlines/index.rss'),
  array('Station' => 'daily mail','Channel' => 'market','Category' => 'market','Url' => 'http://www.dailymail.co.uk/money/market-data.rss')
);
?>